name: driver_ipc_dart
description: Bindings for the drivers IPC interface.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
