[env]
BUILD_FLAGS = "--debug"
BUILD_OUT_DIR = '''build\windows\x64\runner\Debug'''

[env.prod]
BUILD_OUT_DIR = '''build\windows\x64\runner\Release'''
BUILD_FLAGS = "--release"

[tasks.copy]
dependencies = ["harvest"]
script = ['''
    if not exist "..\\target\\output\\vddc" (
        echo Directory not found, creating it...
        mkdir ..\\target\\output\\vddc
    ) else (
        echo Directory found, cleaning it...
        del /S /Q /F ..\\target\\output\\vddc\\*
    )
    ''', '''
        xcopy %BUILD_OUT_DIR%\ ..\target\output\vddc\ /E
    ''']

[tasks.generate]
script = '''
    cargo make %PROFILE% --cwd ..\driver-ipc-dart generate
    '''

[tasks.build]
dependencies = ["generate"]
script = "flutter build windows %BUILD_FLAGS%"

[tasks.harvest]
script = '''%WIX%\bin\heat.exe dir %BUILD_OUT_DIR%\ -o ../target/wix/vddc_files.wxs -dr APPLICATIONFOLDER -ag -sfrag -srd -suid -cg VDDC -var env.VDDC_OUT_PATH'''

[config]
skip_core_tasks = true
