name: virtual_display_driver_control
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  driver_ipc_dart:
    path: ../driver-ipc-dart
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  window_manager: ^0.3.8

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
