name: vdd
description: Control virtual-display-rs using Dart
version: 0.1.0
repository: https://github.com/MolotovCherry/virtual-display-rs/tree/master/rust/bindings/dart

environment:
  sdk: ^3.4.3

dependencies:
  flutter_rust_bridge: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  native_assets_cli: ^0.7.2
  test: ^1.24.0
